USE DATABASE NYC_TAXI;
USE SCHEMA PUBLIC;
USE WAREHOUSE FINAL;

/* ============================================================
   Drop staging views
   ============================================================ */

DROP VIEW IF EXISTS TABLEAU_RIDES_BASE_STAGING;
DROP VIEW IF EXISTS TABLEAU_RIDES_OVER_TIME_STAGING;
DROP VIEW IF EXISTS TABLEAU_RIDES_OVER_DAY_STAGING;
DROP VIEW IF EXISTS TABLEAU_AVG_RIDES_PER_DAY_OF_WEEK_STAGING;
DROP VIEW IF EXISTS TABLEAU_RIDES_BY_WEATHER_STAGING;
DROP VIEW IF EXISTS TABLEAU_PRECIPITATION_VS_RIDES_STAGING;
DROP VIEW IF EXISTS TABLEAU_TEMPERATURE_VS_RIDES_STAGING;
DROP VIEW IF EXISTS TABLEAU_HUMIDITY_VS_RIDES_STAGING;
DROP VIEW IF EXISTS TABLEAU_PICKUP_DROPOFF_HEATMAP_STAGING;
DROP VIEW IF EXISTS TABLEAU_DASHBOARD_FILTERS_STAGING;

/* ============================================================
   Drop staging table
   ============================================================ */

DROP TABLE IF EXISTS RIDES_RAW_STAGING;
