USE DATABASE NYC_TAXI;
USE SCHEMA PUBLIC;
USE WAREHOUSE FINAL;

/* ============================================================
   Promote staging table to production
   ============================================================ */

CREATE OR REPLACE TABLE RIDES_RAW AS
SELECT * FROM RIDES_RAW_STAGING;

/* ============================================================
   Promote staging Tableau views to production
   ============================================================ */

CREATE OR REPLACE VIEW TABLEAU_RIDES_BASE AS
SELECT * FROM TABLEAU_RIDES_BASE_STAGING;

CREATE OR REPLACE VIEW TABLEAU_RIDES_OVER_TIME AS
SELECT * FROM TABLEAU_RIDES_OVER_TIME_STAGING;

CREATE OR REPLACE VIEW TABLEAU_RIDES_OVER_DAY AS
SELECT * FROM TABLEAU_RIDES_OVER_DAY_STAGING;

CREATE OR REPLACE VIEW TABLEAU_AVG_RIDES_PER_DAY_OF_WEEK AS
SELECT * FROM TABLEAU_AVG_RIDES_PER_DAY_OF_WEEK_STAGING;

CREATE OR REPLACE VIEW TABLEAU_RIDES_BY_WEATHER AS
SELECT * FROM TABLEAU_RIDES_BY_WEATHER_STAGING;

CREATE OR REPLACE VIEW TABLEAU_PRECIPITATION_VS_RIDES AS
SELECT * FROM TABLEAU_PRECIPITATION_VS_RIDES_STAGING;

CREATE OR REPLACE VIEW TABLEAU_TEMPERATURE_VS_RIDES AS
SELECT * FROM TABLEAU_TEMPERATURE_VS_RIDES_STAGING;

CREATE OR REPLACE VIEW TABLEAU_HUMIDITY_VS_RIDES AS
SELECT * FROM TABLEAU_HUMIDITY_VS_RIDES_STAGING;

CREATE OR REPLACE VIEW TABLEAU_PICKUP_DROPOFF_HEATMAP AS
SELECT * FROM TABLEAU_PICKUP_DROPOFF_HEATMAP_STAGING;

CREATE OR REPLACE VIEW TABLEAU_DASHBOARD_FILTERS AS
SELECT * FROM TABLEAU_DASHBOARD_FILTERS_STAGING;
